### ISSUE TITLE
nao_phase_provider doesn't  seem to be working.

### ISSUE THREAD

**Issue by m4n1c22** [ijnek/walk#16] opened 2023-05-29 15:34 UTC
I followed the instructions specified in your readme and I get the following warning:

`[WARN] [1685374327.764195779] [Walk]: Notified of a phase, but no change has taken place. Ignoring.`

I have ros2 humble running on my machine. I have already installed the nao_phase_provider, nao_ik and rccs3dnao packages. 

Please let me know what I need to do to make this working.

On side note, I am new to ros and I am just getting to know about the nao robots.

**Comment by ijnek** [comment] 2023-06-05 00:14
Hi @m4n1c22, welcome to the project, and thanks for trying this package out. I noticed your comment earlier in the week, but haven't found the time to reproduce the problem yet.

As mentioned in the README, this package isn't quite ready for usage yet but I would be happy to work together to make it ready for usage. I think it is a good starting point for making the nao robot walk around, and is partially based on the rUNSWift walk.

Right now, I can think of two potential problems:
* there is an issue with the nodes communicating (ie. wrong topics between pub/sub)
* or there is a behavioral issue in the walk (ie. the walk is stuck in a left or right phase and can't get out of it)

I will try and give it a run and see how i go asap.

**Comment by ijnek** [comment] 2023-06-06 00:55
I just gave this a run, and despite the

``[WARN] [1685374327.764195779] [Walk]: Notified of a phase, but no change has taken place. Ignoring.``

warning message printing out, I see the robot walking around fine. Here's a [video](https://youtu.be/NgEADQKCOk0)

When introspecting the nods using rqt's node graph, you should expect something similar to this:

![image](https://github.com/ijnek/walk/assets/18237662/128432f6-3305-43ab-9719-56114686e3c1)

**Comment by m4n1c22** [comment] 2023-06-06 12:06
@ijnek Thanks for getting back to me.
I had made an alternative installation with another package of yours [team_ijnek](https://github.com/ijnek/team_ijnek). This package installation was done two days prior to your first reply. With this package I am able to make movement of the joints and also kick with the feet. However, walk doesn't show any warnings anymore and no walking happens for me on the screen. 
I have attached the screenshot of my terminal screens for you to get an idea of what is happening when I run the walk package now.

![Screenshot from 2023-06-06 12-50-07](https://github.com/ijnek/walk/assets/8198508/62b96be4-a62c-4453-a950-841acfaf5531)

Please let me know what might be going wrong.

If I can't fix this, may I know if I could somehow use the `/motion/sole_poses` topic and publish parameters where I could move the robot manually with the command `ros2 topic pub /motion/sole_poses <something> <params>`. 

I am eagerly waiting for your input.

**Comment by ijnek** [comment] 2023-06-06 22:10
Thanks for the screenshot. Could you also please send a screenshot of rqt's node graph, like i sent in the previous comment?

**Comment by m4n1c22** [comment] 2023-06-07 05:36
Below you will find the screenshot of all terminal sessions along with rqt node graph.

![image](https://github.com/ijnek/walk/assets/8198508/b127f8d9-b99c-4c1a-827d-9ab626170177)

![image](https://github.com/ijnek/walk/assets/8198508/d0398cee-939b-48f1-b183-cecabfbd7db7)

**Comment by ijnek** [comment] 2023-06-08 01:32
In your rqt node graph, there are missing arrows compared to the one I posted between
* /teleop_twist_keyboard node -> /Walk node
* /nao_phase_provider node -> /Walk node

This is due to the topic name not matching. You have probably forgotten the topic remapping arguments for nao_phase_provider and teleop_twist_keyboard:

Make sure you are running nao_phase_provider with: 
```sh
ros2 run nao_phase_provider nao_phase_provider --ros-args -r fsr:=/sensors/fsr
```

and the teleop_twist_keyboard with:
```sh
ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap cmd_vel:=target
```

**Comment by m4n1c22** [comment] 2023-06-09 08:43
I tried the same instructions like you said. However, I get the same rqt graph as above.

**Comment by ijnek** [comment] 2023-06-09 22:57
Hmm... this might be a stupid question, but did you try moving the camera around to check that the robot is showing up in simulation? In rcssserver3d, by default the robot gets launched near the base line and not near the centre circle.

**Comment by m4n1c22** [comment] 2023-06-10 20:20
I checked and robot is showing up in the base line. If you launch the player on the left side team it will show up on the left top corner. This is what I have observed so far.

**Comment by ijnek** [comment] 2023-06-13 02:11
I have a strong suspicion that the topic names aren't matching between the nodes.

What do you get with:
```
ros2 node info /nao_phase_provider
```

```
ros2 node info /teleop_twist_keyboard
```

```
ros2 node info /rcss3d_nao
```

**Comment by m4n1c22** [comment] 2023-06-15 21:37
The output from:

 `ros2 node info /nao_phase_provider`

```
/nao_phase_provider
  Subscribers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /sensors/fsr: nao_sensor_msgs/msg/FSR
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /phase: biped_interfaces/msg/Phase
    /rosout: rcl_interfaces/msg/Log
  Service Servers:
    /nao_phase_provider/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /nao_phase_provider/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /nao_phase_provider/get_parameters: rcl_interfaces/srv/GetParameters
    /nao_phase_provider/list_parameters: rcl_interfaces/srv/ListParameters
    /nao_phase_provider/set_parameters: rcl_interfaces/srv/SetParameters
    /nao_phase_provider/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:
```


`ros2 node info /teleop_twist_keyboard`

```
/teleop_twist_keyboard
  Subscribers:

  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /rosout: rcl_interfaces/msg/Log
    /target: geometry_msgs/msg/Twist
  Service Servers:
    /teleop_twist_keyboard/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /teleop_twist_keyboard/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /teleop_twist_keyboard/get_parameters: rcl_interfaces/srv/GetParameters
    /teleop_twist_keyboard/list_parameters: rcl_interfaces/srv/ListParameters
    /teleop_twist_keyboard/set_parameters: rcl_interfaces/srv/SetParameters
    /teleop_twist_keyboard/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:
```

`ros2 node info /rcss3d_nao`

```
/rcss3d_nao
  Subscribers:
    /effectors/joint_positions: nao_command_msgs/msg/JointPositions
    /parameter_events: rcl_interfaces/msg/ParameterEvent
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /rosout: rcl_interfaces/msg/Log
    /sensors/accelerometer: nao_sensor_msgs/msg/Accelerometer
    /sensors/angle: nao_sensor_msgs/msg/Angle
    /sensors/gyroscope: nao_sensor_msgs/msg/Gyroscope
    /sensors/joint_positions: nao_sensor_msgs/msg/JointPositions
  Service Servers:
    /rcss3d_nao/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /rcss3d_nao/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /rcss3d_nao/get_parameters: rcl_interfaces/srv/GetParameters
    /rcss3d_nao/list_parameters: rcl_interfaces/srv/ListParameters
    /rcss3d_nao/set_parameters: rcl_interfaces/srv/SetParameters
    /rcss3d_nao/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:
```

**Comment by ijnek** [comment] 2023-06-16 01:16
For some reason there is a missing publisher in rcss3d_nao node.
The following is missing:
`/sensors/fsr: nao_sensor_msgs/msg/FSR`

Did you install rcss3d_nao as a binary, or are you compiling it from source? If you're compiling from source, does your branch match the [humble branch](https://github.com/ros-sports/rcss3d_nao/blob/humble/src/rcss3d_nao_node.cpp)?

Since I think the issue is in rcss3d_nao, the next step would to enable the debug logs in rcss3d_nao by running ``ros2 run rcss3d_nao rcss3d_nao --ros-args --log-level DEBUG``, and see what the node outputs about creating the publisher.

I have also realized in your setup, the name of the node is "rcss3d_nao", whereas in my setup, the node is "rcss3d_nao_node". This might just be because you are renaming the node or something though.

**Comment by m4n1c22** [comment] 2023-06-20 18:39
I have compiled rcss3d_nao from source and using the branch humble.

![image](https://github.com/ijnek/walk/assets/8198508/8d057155-7089-4544-bf2d-876705f292d2)


Screenshot of logs when running all the pkgs with log-level DEBUG.

top left is log for rcss3d_nao, bottom left is nao_ik, one middle is walk, right most one is log of phase_provider.

**Comment by m4n1c22** [comment] 2023-06-20 20:42
I have managed to make it work. It seems something from your team_ijnek code was interfering with the setup. I disabled that code and walking worked perfectly fine. 

I have a question now, if I need to port the implementation to an actual nao robot. What do I need to do?

**Comment by ijnek** [comment] 2023-06-22 01:11
Great! Let's close this off question as this is getting long. Please make sure you have updated code across the repositories, as there have been some recent changes in some repos.

> I have a question now, if I need to port the implementation to an actual nao robot. What do I need to do?

Could you post this in https://cross.forum.robocup.org/ where we could discuss how to do this?

**Closed as completed** 2023-06-22 01:11 UTC
